print ('Lyshane Ola De Los Reyes')
print ('Malusak, Boac, Marinduque')
print ('December 13, 1998')
print ('Marinduque State College')
print ('Bachelor of Science in Information Technology')
print ('2-A')
print ('Watching Movie')
print ('Listening to Music')
print ('Eating')
print ('Playing Online Games')
print ('Photography')